from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
RELEASE = "cap-digest-0.1.0-alpha"
OUTPUT = ROOT / "release-artifacts" / RELEASE

CAP_DIGEST_SCHEMAS = [
    "cap.conformance_report.v1.schema.json",
    "cap.contract_response.v1.schema.json",
    "cap.digest.v1.schema.json",
    "cap.digest_pack.v1.schema.json",
    "cap.digest_patch.v1.schema.json",
    "cap.field.v1.schema.json",
    "cap.field_catalog.v1.schema.json",
    "cap.gate_result.v1.schema.json",
    "cap.manifest.v1.schema.json",
    "cap.pack_conformance_report.v1.schema.json",
    "cap.validation_result.v1.schema.json",
]

CAP_DIGEST_FIXTURES = [
    "basic-table",
    "digest-text-negative",
    "followup-basic",
    "pack-table-basic",
    "security-adversarial",
]


def git_value(*args: str) -> str:
    result = subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True, text=True)
    return result.stdout.strip()


def copy_tree(src: Path, dst: Path) -> None:
    shutil.copytree(src, dst, dirs_exist_ok=True)


def write(path: Path, text: str) -> None:
    path.write_text(text.strip() + "\n", encoding="utf-8")


def main() -> int:
    if OUTPUT.exists():
        shutil.rmtree(OUTPUT)
    (OUTPUT / "schemas").mkdir(parents=True)
    (OUTPUT / "fixtures").mkdir(parents=True)

    for schema in CAP_DIGEST_SCHEMAS:
        shutil.copy2(ROOT / "schemas" / schema, OUTPUT / "schemas" / schema)
    for fixture in CAP_DIGEST_FIXTURES:
        copy_tree(ROOT / "fixtures" / fixture, OUTPUT / "fixtures" / fixture)

    subprocess.run(
        [
            sys.executable,
            "reference/python/scripts/validate_fixtures.py",
            "--scope",
            "digest",
            "--report",
            str(OUTPUT / "conformance-report.json"),
        ],
        cwd=ROOT,
        check=True,
    )

    release_commit = git_value("rev-parse", f"{RELEASE}^{{}}")
    write(
        OUTPUT / "reference-version.txt",
        f"""
release: {RELEASE}
releaseTagCommit: {release_commit}
referenceImplementation: reference/python
conformanceReport: conformance-report.json
schemaScope: CAP-Digest only; schemas/core is excluded
fixtureScope: basic-table, digest-text-negative, followup-basic, pack-table-basic, security-adversarial
""",
    )
    write(
        OUTPUT / "release-notes.md",
        """
# CAP-Digest 0.1.0-alpha

This alpha covers digest text, DigestManifest, DigestEvidence validation,
follow-up gate behavior, Digest Packs, schemas, fixtures, and reference checks.

Executable coverage currently reaches CAP-Digest Level 0/1 for table assembly,
Level 2 for the follow-up gate, and Level 3 for table-basic Digest Pack metadata
loading.

Included fixture families:

- `fixtures/basic-table`
- `fixtures/digest-text-negative`
- `fixtures/followup-basic`
- `fixtures/pack-table-basic`
- `fixtures/security-adversarial`

The Python reference implementation is an experimental executable companion,
not a production SDK.

CAP-Core remains non-normative draft-track material only. Core schemas, the
local-analysis fixture, RunEvidence, runtime binding, service binding, and the
policy model are not stable CAP-Digest conformance requirements.
""",
    )
    write(
        OUTPUT / "known-limitations.md",
        """
# Known Limitations

- Only the table source type has executable coverage.
- The Python reference implementation is intentionally minimal.
- JSON schemas are draft assets.
- Broader JSON Schema validation across every fixture shape is post-alpha
  hardening work.
- Remote, credentialed, and large-source fixtures are out of scope.
- CAP-Core schemas, fixtures, RunEvidence, runtime binding, service binding,
  and policy model are excluded from CAP-Digest release conformance.
""",
    )
    write(
        OUTPUT / "README.md",
        """
# CAP-Digest 0.1.0-alpha Release Artifacts

This directory packages the CAP-Digest alpha materials an external implementer
needs without browsing the full repository.

## Layout

- `schemas/` contains CAP-Digest JSON schemas used by this alpha package.
- `fixtures/` contains the CAP-Digest alpha fixture families.
- `conformance-report.json` is generated by the reference implementation with
  `python reference/python/scripts/validate_fixtures.py --scope digest --report`.
- `release-notes.md` and `known-limitations.md` mirror the alpha release scope.
- `reference-version.txt` records the release tag commit and conformance scope.

## Excluded

`schemas/core/`, `fixtures/core/`, RunEvidence, runtime binding, service
binding, and Core policy records are CAP-Core draft-track materials. They are
not CAP-Digest alpha conformance artifacts.
""",
    )

    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
